name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Release Name"
        required: true
        type: string
      is_major:
        description: "Is Major Release?"
        type: boolean
        default: false
        required: true




