# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Release Name"
        required: true
        type: string
      is_major:
        description: "Is Major Release?"
        type: boolean
        default: false
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      # checkout code
      - uses: actions/checkout@v3

      # get the current version
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      
      # update the version (major or minor)


      # (future) make sure there is no other release active
      
      # create branch - release/

      # push the change





